# Generated by Django 4.2.11 on 2024-04-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BobcatConApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roommate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('move_in_date', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
