# Generated by Django 4.2.11 on 2024-04-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BobcatConApp', '0002_roommate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textbooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
