# Generated by Django 4.2.11 on 2024-05-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BobcatConApp', '0006_loginperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
