# Generated by Django 5.0.4 on 2024-05-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BobcatConApp', '0007_mealplanpurchasehistory_textbookpurchasehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplanpurchasehistory',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='textbookpurchasehistory',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
