# Generated by Django 4.2.11 on 2024-05-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BobcatConApp', '0007_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('selected', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='category',
        ),
        migrations.AddField(
            model_name='activity',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
