# Generated by Django 4.2.11 on 2024-05-02 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BobcatConApp', '0008_party_alter_activity_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Party',
        ),
    ]
