# Generated by Django 4.2.11 on 2024-05-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BobcatConApp', '0010_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
