# Generated by Django 4.2.11 on 2024-05-02 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BobcatConApp', '0009_ticketpurchasehistory'),
        ('BobcatConApp', '0011_event_selected'),
    ]

    operations = [
    ]
